let rc= "                    <@> Report Card <@>";
console.log(rc);
let gap="                    ...................";
console.log(gap);
let gap10="---------------------------------------------------------------";
console.log(gap10);
let name= "Name: KJ";
let gap1="---------------------------------------------------------------";
let school= "School: JNV";
let gap2="---------------------------------------------------------------";
let grade= "Grade: Highschool";
let gap3="---------------------------------------------------------------";
let section= "Section: B";
let gap4="---------------------------------------------------------------";
let rn="Roll no: 16";
let gap5="---------------------------------------------------------------";
let sn= "S no.   Subjects        Marks Obtained        Total marks";
let gap6="---------------------------------------------------------------";
let sn1=" 1      Maths               350                   500";
let gap7="---------------------------------------------------------------";
let sn2=" 2      English             370                   500";
let gap8="---------------------------------------------------------------";
let sn3=" 3      CS                  400                   500";
let gap9="---------------------------------------------------------------";
console.log(name);
console.log(gap1);
console.log(school);
console.log(gap2);
console.log(grade);
console.log(gap3);
console.log(section);
console.log(gap4);
console.log(rn);
console.log(gap5);
console.log(sn);
console.log(gap6);
console.log(sn1);
console.log(gap7);
console.log(sn2);
console.log(gap8);
console.log(sn3);
console.log(gap9);